# Section 2.4 — Phylogenetic inference (IQ-TREE v3.1.2)
# Run from: BM954-Research-Project/sequences/
# Input: uniprot_aligneddd.trimal.fasta
# Note: seed 67043 was auto-generated by IQ-TREE's SPRNG generator, not manually set

iqtree -s uniprot_aligneddd.trimal.fasta -m TEST
iqtree -s uniprot_aligneddd.trimal.fasta -m DAYHOFF+G4 -B 1000 --redo-tree

